package com.gdd.tolittlepart.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.gdd.tolittlepart.entity.NewsChannelTable;
import com.gdd.tolittlepart.entity.StudentBean;

import com.gdd.tolittlepart.greendao.NewsChannelTableDao;
import com.gdd.tolittlepart.greendao.StudentBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsChannelTableDaoConfig;
    private final DaoConfig studentBeanDaoConfig;

    private final NewsChannelTableDao newsChannelTableDao;
    private final StudentBeanDao studentBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsChannelTableDaoConfig = daoConfigMap.get(NewsChannelTableDao.class).clone();
        newsChannelTableDaoConfig.initIdentityScope(type);

        studentBeanDaoConfig = daoConfigMap.get(StudentBeanDao.class).clone();
        studentBeanDaoConfig.initIdentityScope(type);

        newsChannelTableDao = new NewsChannelTableDao(newsChannelTableDaoConfig, this);
        studentBeanDao = new StudentBeanDao(studentBeanDaoConfig, this);

        registerDao(NewsChannelTable.class, newsChannelTableDao);
        registerDao(StudentBean.class, studentBeanDao);
    }
    
    public void clear() {
        newsChannelTableDaoConfig.clearIdentityScope();
        studentBeanDaoConfig.clearIdentityScope();
    }

    public NewsChannelTableDao getNewsChannelTableDao() {
        return newsChannelTableDao;
    }

    public StudentBeanDao getStudentBeanDao() {
        return studentBeanDao;
    }

}
